/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paintapp;


import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.AffineTransform;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.DefaultListModel;


/**
 *
 * @author Dodo
 */

public class Frame extends javax.swing.JFrame {

    static boolean filled=false;
    static UndoRedo undo,event;

    @Override
    public void paint(Graphics g) {
        super.paint(g); //To change body of generated methods, choose Tools | Templates.
    }
      
    /**
     * Creates new form Frame
     */
    
    public Frame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paintArea1 = new paintapp.PaintArea();
        jScrollBar1 = new javax.swing.JScrollBar();
        LineButton = new javax.swing.JButton();
        EllipseButton = new javax.swing.JButton();
        RectButton = new javax.swing.JButton();
        FilledCheckBox = new javax.swing.JCheckBox();
        SquareButton = new javax.swing.JButton();
        CircleButton = new javax.swing.JButton();
        DeleteAllButton = new javax.swing.JButton();
        TriangleButton = new javax.swing.JButton();
        SelectButton = new javax.swing.JButton();
        DeleteSelectedButton = new javax.swing.JButton();
        ColorjButton = new javax.swing.JButton();
        CopyjButton = new javax.swing.JButton();
        ResizejButton = new javax.swing.JButton();
        UndojButton = new javax.swing.JButton();
        RedojButton = new javax.swing.JButton();
        Rotate_Button = new javax.swing.JButton();
        currentColorLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        HistoryList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(255, 153, 0));

        paintArea1.setBackground(new java.awt.Color(255, 255, 255));
        paintArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        paintArea1.setMinimumSize(new java.awt.Dimension(17, 200));

        jScrollBar1.setValue(paintArea1.getHeight());
        jScrollBar1.setVisibleAmount(50);
        jScrollBar1.setMinimumSize(new java.awt.Dimension(17, 200));

        javax.swing.GroupLayout paintArea1Layout = new javax.swing.GroupLayout(paintArea1);
        paintArea1.setLayout(paintArea1Layout);
        paintArea1Layout.setHorizontalGroup(
            paintArea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paintArea1Layout.createSequentialGroup()
                .addGap(0, 953, Short.MAX_VALUE)
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        paintArea1Layout.setVerticalGroup(
            paintArea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
        );

        LineButton.setBackground(new java.awt.Color(204, 204, 204));
        LineButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/straightness.png"))); // NOI18N
        LineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LineButtonActionPerformed(evt);
            }
        });

        EllipseButton.setBackground(new java.awt.Color(204, 204, 204));
        EllipseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/ellipse-50.png"))); // NOI18N
        EllipseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EllipseButtonActionPerformed(evt);
            }
        });

        RectButton.setBackground(new java.awt.Color(204, 204, 204));
        RectButton.setForeground(new java.awt.Color(255, 255, 255));
        RectButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/rectangle.gif"))); // NOI18N
        RectButton.setToolTipText("");
        RectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RectButtonActionPerformed(evt);
            }
        });

        FilledCheckBox.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        FilledCheckBox.setText("Filled");
        FilledCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilledCheckBoxActionPerformed(evt);
            }
        });

        SquareButton.setBackground(new java.awt.Color(204, 204, 204));
        SquareButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/square.gif"))); // NOI18N
        SquareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SquareButtonActionPerformed(evt);
            }
        });

        CircleButton.setBackground(new java.awt.Color(204, 204, 204));
        CircleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/circle38a.gif"))); // NOI18N
        CircleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CircleButtonActionPerformed(evt);
            }
        });

        DeleteAllButton.setBackground(new java.awt.Color(204, 204, 204));
        DeleteAllButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/trash30.gif"))); // NOI18N
        DeleteAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteAllButtonActionPerformed(evt);
            }
        });

        TriangleButton.setBackground(new java.awt.Color(204, 204, 204));
        TriangleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/right-triangle-icon-24623.png"))); // NOI18N
        TriangleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TriangleButtonActionPerformed(evt);
            }
        });

        SelectButton.setBackground(new java.awt.Color(204, 204, 204));
        SelectButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/movinghand.gif"))); // NOI18N
        SelectButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SelectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectButtonActionPerformed(evt);
            }
        });

        DeleteSelectedButton.setBackground(new java.awt.Color(204, 204, 204));
        DeleteSelectedButton.setText("Delete selected");
        DeleteSelectedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteSelectedButtonActionPerformed(evt);
            }
        });

        ColorjButton.setBackground(new java.awt.Color(204, 204, 204));
        ColorjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Rainbow.png"))); // NOI18N
        ColorjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColorjButtonActionPerformed(evt);
            }
        });

        CopyjButton.setBackground(new java.awt.Color(204, 204, 204));
        CopyjButton.setText("Copy");
        CopyjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CopyjButtonActionPerformed(evt);
            }
        });

        ResizejButton.setBackground(new java.awt.Color(204, 204, 204));
        ResizejButton.setText("Resize");
        ResizejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResizejButtonActionPerformed(evt);
            }
        });

        UndojButton.setBackground(new java.awt.Color(204, 204, 204));
        UndojButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/undo.png"))); // NOI18N
        UndojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UndojButtonActionPerformed(evt);
            }
        });

        RedojButton.setBackground(new java.awt.Color(204, 204, 204));
        RedojButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/redo.png"))); // NOI18N
        RedojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RedojButtonActionPerformed(evt);
            }
        });

        Rotate_Button.setBackground(new java.awt.Color(204, 204, 204));
        Rotate_Button.setText("Rotate");
        Rotate_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rotate_ButtonActionPerformed(evt);
            }
        });

        currentColorLabel.setBackground(new java.awt.Color(0, 0, 0));
        currentColorLabel.setForeground(new java.awt.Color(255, 255, 255));
        currentColorLabel.setOpaque(true);

        jLabel1.setBackground(new java.awt.Color(51, 255, 255));
        jLabel1.setFont(new java.awt.Font("Swis721 BlkOul BT", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 204));
        jLabel1.setText("Paint");

        jScrollPane1.setViewportView(HistoryList);

        jLabel2.setBackground(new java.awt.Color(255, 0, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 204));
        jLabel2.setText("History");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(395, 395, 395)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(FilledCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ColorjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(currentColorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(135, 135, 135))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(SquareButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(EllipseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(RectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(CircleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(LineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(CopyjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(SelectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(44, 44, 44)))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TriangleButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Rotate_Button, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ResizejButton))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DeleteAllButton)
                                .addGap(32, 32, 32))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(176, 176, 176)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DeleteSelectedButton)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(UndojButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RedojButton))))))
                    .addComponent(paintArea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TriangleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RectButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(EllipseButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CircleButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(SquareButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(LineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(FilledCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(currentColorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ColorjButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(SelectButton)
                                            .addComponent(ResizejButton))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Rotate_Button)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(CopyjButton)
                                                .addGap(4, 4, 4))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(DeleteAllButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(DeleteSelectedButton)
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(UndojButton)
                                            .addComponent(RedojButton))))
                                .addGap(14, 14, 14)))
                        .addComponent(paintArea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LineButtonActionPerformed
        // TODO add your handling code here:
        paintArea1.selected=null;
        paintArea1.currentShape=1;
                        paintArea1.mode=0;
                        
     

    }//GEN-LAST:event_LineButtonActionPerformed

    private void EllipseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EllipseButtonActionPerformed
        // TODO add your handling code here:
        paintArea1.selected=null;
         paintArea1.currentShape=2;                       
         
         
                         paintArea1.mode=0;
       
    }//GEN-LAST:event_EllipseButtonActionPerformed

    private void RectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RectButtonActionPerformed
        // TODO add your handling code here:
        paintArea1.selected=null;
         paintArea1.currentShape=3;
          
                         paintArea1.mode=0;

    }//GEN-LAST:event_RectButtonActionPerformed

    private void SquareButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SquareButtonActionPerformed
        // TODO add your handling code here:
        paintArea1.selected=null;
        paintArea1.currentShape=4;
        
                paintArea1.mode=0;

    }//GEN-LAST:event_SquareButtonActionPerformed

    private void CircleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CircleButtonActionPerformed
        // TODO add your handling code here:
        paintArea1.selected=null;
                paintArea1.currentShape=5;
                
                        paintArea1.mode=0;


    }//GEN-LAST:event_CircleButtonActionPerformed

    private void DeleteAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteAllButtonActionPerformed
        // TODO add your handling code here:
        paintArea1.deleteAll();
    }//GEN-LAST:event_DeleteAllButtonActionPerformed

    private void TriangleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TriangleButtonActionPerformed
        // TODO add your handling code here:
        paintArea1.selected=null;
         paintArea1.currentShape=6;
                 paintArea1.mode=0;

    }//GEN-LAST:event_TriangleButtonActionPerformed

    private void SelectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectButtonActionPerformed
        // TODO add your handling code here:
        paintArea1.mode=1;        
        
    }//GEN-LAST:event_SelectButtonActionPerformed

    private void DeleteSelectedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteSelectedButtonActionPerformed
        // TODO add your handling code here:
       paintArea1.deleteSelected();
    }//GEN-LAST:event_DeleteSelectedButtonActionPerformed

    private void ColorjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorjButtonActionPerformed
      paintArea1.currentColor=JColorChooser.showDialog(null,  "Pick a Fill", paintArea1.currentColor);
      currentColorLabel.setBackground(paintArea1.currentColor);
      if(paintArea1.selected!=null){
          paintArea1.selected.shapeColor=paintArea1.currentColor;
          if(paintArea1.selected.filled==false && FilledCheckBox.isSelected()){ 
              paintArea1.selected.filled=true;
                        }
          else if(paintArea1.selected.filled==true && !FilledCheckBox.isSelected()){
          paintArea1.selected.filled=false;}
          paintArea1.selected=null;
          
          
          }// TODO add your handling code here:
    }//GEN-LAST:event_ColorjButtonActionPerformed

    private void FilledCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilledCheckBoxActionPerformed
        // TODO add your handling code here:
        filled = FilledCheckBox.isSelected(); 
    }//GEN-LAST:event_FilledCheckBoxActionPerformed

    private void CopyjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CopyjButtonActionPerformed
if(paintArea1.selected!=null){     
       Shape shape=(Shape)paintArea1.selected.clone();
      Graphics temp=this.getGraphics();        
      paintArea1.copyPaintComponent(shape, temp);

        
}
    }//GEN-LAST:event_CopyjButtonActionPerformed

    private void ResizejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResizejButtonActionPerformed
        // TODO add your handling code here:
      if(paintArea1.selected!=null){
        Shape shape=(Shape)paintArea1.selected;
      Graphics temp=paintArea1.getGraphics();  
               Graphics2D g2d = (Graphics2D)temp;
               Graphics2D g2dcopy = (Graphics2D)g2d.create(); 
        AffineTransform transform = new AffineTransform();
        
        PaintArea.resizePaintComponent(shape, g2dcopy);
        AffineTransform old = g2d.getTransform();
        
             g2d.transform(transform);
             repaint();
          
        }
        
    }//GEN-LAST:event_ResizejButtonActionPerformed

    private void Rotate_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rotate_ButtonActionPerformed
        // TODO add your handling code here:
        if(paintArea1.selected!=null){
        Shape shape=(Shape)paintArea1.selected;
        
      Graphics temp=paintArea1.getGraphics();        
              String degrees=JOptionPane.showInputDialog("Please Enter degrees to be rotated");
        double doubledegree=Double.parseDouble(degrees);// convert string to double
       
               Graphics2D g2d = (Graphics2D)temp;
           AffineTransform old = g2d.getTransform();
           AffineTransform trans = g2d.getTransform();
        g2d.rotate(Math.toRadians(doubledegree), shape.getStartPoint().getX(), shape.getStartPoint().getY());
             g2d.setTransform(trans);
          //draw shape (will be rotated)            
paintArea1.paintComponent(temp, shape);
        }
    }//GEN-LAST:event_Rotate_ButtonActionPerformed

    private void RedojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RedojButtonActionPerformed
        // TODO add your handling code here:
        paintArea1.redo();
        
    }//GEN-LAST:event_RedojButtonActionPerformed

    private void UndojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UndojButtonActionPerformed
        // TODO add your handling code here:
        paintArea1.undo();

    }//GEN-LAST:event_UndojButtonActionPerformed
public void Update(){
    DefaultListModel l =new DefaultListModel();
    HistoryList.setModel(l);
    for(int i=0;i< paintArea1.History.size();i++)
    {     
        l.addElement(paintArea1.History.get(i));
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CircleButton;
    private javax.swing.JButton ColorjButton;
    private javax.swing.JButton CopyjButton;
    private javax.swing.JButton DeleteAllButton;
    private javax.swing.JButton DeleteSelectedButton;
    private javax.swing.JButton EllipseButton;
    private javax.swing.JCheckBox FilledCheckBox;
    private javax.swing.JList<String> HistoryList;
    private javax.swing.JButton LineButton;
    private javax.swing.JButton RectButton;
    private javax.swing.JButton RedojButton;
    private javax.swing.JButton ResizejButton;
    private javax.swing.JButton Rotate_Button;
    private javax.swing.JButton SelectButton;
    private javax.swing.JButton SquareButton;
    private javax.swing.JButton TriangleButton;
    private javax.swing.JButton UndojButton;
    private javax.swing.JLabel currentColorLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private paintapp.PaintArea paintArea1;
    // End of variables declaration//GEN-END:variables
}
